name: Bump

on:
  pull_request:
    types: [closed]
    branches:
      - main

jobs:
  bump:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: create tag
        run: |
          bash ./.github/workflows/scripts/bump.sh ${{ github.head_ref }}